services:
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
    networks:
      - backend_network
    volumes:
      - ./src/backend/src:/app/src
networks:
    backend_network:
        name: backend_network
