services:
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./env/backend.env
    networks:
      - open_baby_network
    volumes:
      - ./src/backend/src:/app/src
      - ./src/backend/test.db:/app/test.db:rw
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./env/frontend.env
    networks:
      - open_baby_network
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
networks:
    open_baby_network:
        name: open_baby_network
