services:
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    environment:
      - ROOT_PATH=/api
    networks:
      - open_baby_network
    volumes:
      - ./src/backend/src:/app/src
      - ./src/backend/test.db:/app/test.db:rw
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    env_file:
      - ./env/frontend.env
    networks:
      - open_baby_network
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - open_baby_network
    depends_on:
      - backend
      - frontend
networks:
    open_baby_network:
        name: open_baby_network