"""Initial migration

Revision ID: 2acdd28299a7
Revises:
Create Date: 2025-08-17 21:38:38.827061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2acdd28299a7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_description"), "events", ["description"], unique=False
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_name"), "events", ["name"], unique=False)
    op.create_table(
        "bottle_feed_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("amount_ml", sa.String(), nullable=False),
        sa.Column("is_formula", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "breast_feed_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("breast_feed_events")
    op.drop_table("bottle_feed_events")
    op.drop_index(op.f("ix_events_name"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_index(op.f("ix_events_description"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
