"""Add pump event

Revision ID: a08be7491865
Revises: e149d8124e0c
Create Date: 2025-09-02 22:56:07.600741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a08be7491865"
down_revision: Union[str, Sequence[str], None] = "e149d8124e0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pump_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("amount_ml", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pump_events")
    # ### end Alembic commands ###
