"""Add diaper events

Revision ID: e149d8124e0c
Revises: 4d34c24e035e
Create Date: 2025-08-26 17:10:28.193292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e149d8124e0c"
down_revision: Union[str, Sequence[str], None] = "4d34c24e035e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diaper_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "diaper_type",
            sa.Enum("PEE", "POOP", "BOTH", name="diapertype"),
            nullable=False,
        ),
        sa.Column(
            "diaper_contents_color",
            sa.Enum("YELLOW", "BROWN", "GREEN", "BLACK", name="diapercontentscolor"),
            nullable=True,
        ),
        sa.Column(
            "diaper_contents_consistency",
            sa.Enum("WATERY", "PASTY", name="diapercontentsconsistency"),
            nullable=True,
        ),
        sa.Column(
            "diaper_contents_size",
            sa.Enum("SMALL", "MEDIUM", "LARGE", name="diapercontentssize"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("diaper_events")
    # ### end Alembic commands ###
